spring:
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://ewallet-postgres:5432/ewallet
    username: postgres
    password: postgres